# Generated by Django 4.1.2 on 2022-10-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
