# Generated by Django 4.1.2 on 2022-10-22 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0003_remove_product_imageurl_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('photo_t', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectApp.product')),
            ],
        ),
    ]
