# Generated by Django 4.1.2 on 2022-10-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0007_remove_product_photos_product_photoload_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interestedFruit',
            field=models.BooleanField(default=False),
        ),
    ]
